version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/utils/malvolio"
    schedule:
      interval: "daily"
