comment: false
github_checks:
    annotations: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths:
          # match any Rust file
          - ".+.rs"
        branches:
          - main
        if_ci_failed: error # ignore
        informational: false
        only_pulls: false
