# uses a faster linker
# note that if you haven't already, you need to install zld (`brew install michaeleisel/zld/zld`)
[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/usr/local/bin/zld",
    "-Csplit-debuginfo=unpacked",
]
