[package]
name = "mercutio"
version = "0.1.0"
authors = ["teymour-aldridge <teymour.aldridge@icloud.com>"]
edition = "2018"

[dependencies]
mercutio_codegen = { path = "../mercutio_codegen" }
malvolio = { path = "../malvolio" }
