name: "Weekly deploy"

on:
  schedule:
    - cron: "0 5 */7 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git remote add gigalixir $GIGALIXIR
          git push -f gigalixir HEAD:refs/heads/master
        env:
          GIGALIXIR: ${{ secrets.GIGALIXIR }}
